### ISSUE TITLE
Regression Testing for Outlier Explorer v1.3.0

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#36]
Confirm basic functionality and new features are working as expected in examples shown below:

Examples using v1.3.0 Release Candidate
[default](http://bl.ocks.org/samussiah/raw/d9ac58a6d9db586ea8335479b6528aa9/)
[customized](http://bl.ocks.org/samussiah/raw/05e677f7b8f0eca0f4bf1f7a54b1aa0e/)

**Basic Functionality (Tested every release)**
- [x] Check all spelling and grammar on the page
- [x] Confirm that the Measure filter is working as expected: when selected, the distribution of observations should change.
- [x] Confirm that the X-axis filter changes the x-axis to the selected variable
- [x] Use a combination of filters to ensure that more than one manipulation can be applied at once
- [x] Confirm that you can view a detailed listing of a participant (small multiples) by clicking on a plot point in the chart: the drop down should provide more information about measures and and visits for the individual

**New Functionality (Tested in V1.3.0 only)**
- [x] (#27) Confirm that plot points marked as queried appear as a different color than other plot points and when clicked, display a message detailing the event and query
- [x] (#23) Confirm that a participant status filter is present and works as expected
- [x] (#22) Confirm that the axes ranges appear consistently when using multiple filters
- [x] (#20) Confirm that the x-axis for visit number only displays one visit number per visit
- [x] (#19) Confirm that the small multiples for a participant includes demographic information (age, sex, race)
- [x] (#18) Confirm that the # of enrolled/randomized individuals is visible on the top of the chart
- [x] (#17) Confirm that there is an option to rotate the x-axis by 45 degrees and that it works as expected?
- [x] (#13) Confirm that the small multiples appear as a consistent size by selecting multiple filters and exploring multiple small multiples for participants
- [x] (#10) Confirm that the "Lab Test" filter is now presented as "Measure"

**Comment by samussiah** [comment]
[default](http://bl.ocks.org/samussiah/raw/d9ac58a6d9db586ea8335479b6528aa9/)
[customized](http://bl.ocks.org/samussiah/raw/05e677f7b8f0eca0f4bf1f7a54b1aa0e/)

**Comment by brittsikora** [comment]
Regression testing notes:
- [ ] Custom example is plotting missing values (#41) 
- [ ] Small multiples in default example are not rendering (#42)

**Comment by brittsikora** [comment]
The issue mentioned above has been fixed - closing this test
